### ISSUE TITLE
Feature request: more string manipulation functions

### ISSUE THREAD

**Issue by Diggsey** [starkat99/widestring-rs#1]
It would really help if some of these features existed on WideStr and WideCStr:
- Slicing/indexing (more than just RangeFull)
- Mutations (remove, pop, trim, etc.)
- String matching (starts_with, ends_with, contains, find, matches, etc.)
- String splitting
- String replacing
- Iteration (iterate by u16, iterate by (char | malformed utf16), iterate with indices)

It would also be nice to better document the behaviour of `to_os_string`/`from_str` on non-windows platforms where there's no canonical 1:1 relationship between an OsString and a WideString.

**Comment by starkat99** [comment]
Yes, I've been mulling over some of these recently, I definitely want this functionality on `WideString`.

Currently, the crate doesn't compile on non-windows platforms. Since I originally made it to work with Windows APIs I didn't bother with other platforms. The relationship could definitely be defined better even for Windows platform.
