### ISSUE TITLE
WideCString/WideString => &str

### ISSUE THREAD

**Issue by norbert78** [starkat99/widestring-rs#3]
Hi there,
this is actually more of a question than an issue but I'm very interested in your opinion. I have been using your WideCString type in a very small rust project and am facing the situation that I have to tranform a variable of type WideCString into a slice of type &str.
I can see various ways of doing so, specifically:
- tranforming from WideCString => std::String (via to_string_lossy()) => &str 
- transforming from WideCString => &[u16] (via as_slice) => &str 

I would be really interested in your perspective in this. What would be the best way to go?
For me this is not only a question of writing code that jst works. I'm currently learning rust and am really interested in writing "good" code (whatever that means). So, I'm trying to understand a little bit more than what I have to....
Thanks
Norbert

**Comment by starkat99** [comment]
The main thing is to be aware of the string encoding, but in general, your best bet is definitely through `WCString::to_string_lossy()` if you know the string to be UTF-16, or mostly UTF-16. Because a wide string is going to be a sequence of `u16` values and a regular Rust string is UTF-8 values, you're going to need to have an owned `String` somewhere along the way, you won't be able to go directly from a `&[u16]` slice to a `&str`. If you're not dealing with UTF-16 values, you'll have to use an external encoding crate to construct the `String` however.

If you're unsure, especially if your wide string comes from Windows, you probably have UTF-16, or at least malformed UTF-16, hence the possibility of a 'lossy' conversion. You can use `WideCString::to_string()` to detect and deal with malformed UTF-16, if needed.
