### ISSUE TITLE
library uses u16 rather than wchar_t

### ISSUE THREAD

**Issue by mberndt123** [starkat99/widestring-rs#9]
I was trying to use this library with a C library that uses `wchar_t*` strings in its API. Unfortunately widestring decided to use `u16` as its “wide character” type, while `wchar_t` is a 32-bit type on Linux.
Any reason why widestring can't just use `wchar_t` as its character type? IMO that would be the sensible thing to do…

**Comment by starkat99** [comment]
wchart_t is an awful mistake, and is why C++ introduced char16_t and char32_t. That does remind me that I want to add a u32 string for this though. It's then pretty trivial to switch between them

**Comment by mberndt123** [comment]
Arguably UTF-16 is also a mistake and yet that is what this library apparently supports. But whether or not it was a mistake is besides the point. The point is: there are libraries out there that use it (e. g. the hidapi library) and there is currently no way to deal with that in a portable way.

**Comment by mberndt123** [comment]
I'm confused at this point. What is the intended use case for this library?

UTF-8 is a variable-length encoding, but in turn you get ASCII compatibility and a compact representation for most western languages. UTF-32 is a fixed-length encoding. UTF-16 OTOH gives you the worst of both worlds: it's variable-length, large and not ASCII-compatible. There's only one reason why one would want to use it: because the API forces you to, which is the case on Windows. On Unix on the other hand nobody uses UTF-16, so why would the widestring crate do that?

**Comment by starkat99** [comment]
Oh no, I totally agree about UTF-16 too. Unfortunately, OsString doesn't actually cut it on Windows, since under the hood OsString is still stored in an 8-bit format (WTF-8 https://simonsapin.github.io/wtf-8/) so there are actually additional conversions on Windows whenever using OsString. This library was actually originally Windows only, thus the lack of UTF-32 options. That said, I've been wanting to have 32-bit strings for a while, and this reminded me. The repo has a new version of crate up with U32String (and a rename of WideString to U16String to be clearer about it). I also added type aliases intended to match typical wchar_t platform usage. Check it out, let me know if it's what you're looking for? I'll put out a new release with this in a little while, once I clean up some details.

**Comment by mberndt123** [comment]
Oh, I see! I didn't know that OsString uses this strange encoding. Now it makes sense.

I took a quick look at your implementation of U32CString and it looks like a copy-pasted version of U16CString. Wouldn't it be more maintainable to make the character type a type parameter and then add some suitable type aliases?

**Comment by starkat99** [comment]
I cleaned up a bunch and published 0.4 with the new string types. https://github.com/starkat99/widestring-rs/releases/tag/v0.4.0

**Comment by mberndt123** [comment]
Cool, thanks
